language: ruby
env:
  - PUPPET_VERSION=4.7.0
  - PUPPET_VERSION=4.7.0
  - PUPPET_VERSION=4.6.2
  - PUPPET_VERSION=4.6.1
  - PUPPET_VERSION=4.5.2
  - PUPPET_VERSION=4.5.2
  - PUPPET_VERSION=4.5.1
  - PUPPET_VERSION=4.5.0
  - PUPPET_VERSION=4.4.2
  - PUPPET_VERSION=4.4.1
  - PUPPET_VERSION=4.4.0
  - PUPPET_VERSION=4.3.2
  - PUPPET_VERSION=4.3.2
  - PUPPET_VERSION=4.3.2
  - PUPPET_VERSION=4.3.1
  - PUPPET_VERSION=4.3.1
  - PUPPET_VERSION=4.3.0
  - PUPPET_VERSION=4.2.3
  - PUPPET_VERSION=4.2.2
  - PUPPET_VERSION=4.2.2
  - PUPPET_VERSION=4.2.2
  - PUPPET_VERSION=4.2.1
  - PUPPET_VERSION=4.2.0
  - PUPPET_VERSION=4.2.0
  - PUPPET_VERSION=4.1.0
  - PUPPET_VERSION=4.0.0
  - PUPPET_VERSION=3.8.1
  - PUPPET_VERSION=3.7.0
rvm:
  - 2.2.0
  - 2.1.0
  - 2.0.0
script:
  - "bundle exec rake spec"
